### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [bhj/KaraokeEternal#12]
Hello @bhj I am a logo designer.  I contribute to open source projects that do not have logo.  I designed a functional logo for karaoke-forever. What do you think? I will wait for feedback. Have a nice day!

![karaoke-forever](https://user-images.githubusercontent.com/36298335/56764293-0c026f00-67ad-11e9-9127-624bb547dac7.jpg)

Readme view;

![kara](https://user-images.githubusercontent.com/36298335/56764389-3fdd9480-67ad-11e9-9f03-af5f8dc9ad46.png)

Website view;

![kara2](https://user-images.githubusercontent.com/36298335/56764563-ae225700-67ad-11e9-9e67-3b6b5093524e.jpg)

**Comment by bhj** [comment]
Apologies for the delay and thank you for the contribution!

My only concern with the mic + infinity symbol is that a friend's karaoke app also uses [something similar](http://demo.karaokes.moe/) so I want to avoid any confusion there. I quite like your typography choices and will try to emulate that in the next documentation update, possibly with the current [application icon](https://github.com/bhj/karaoke-forever/blob/master/assets/app.png) which isn't really a logo but is consistent with the hues used in the app for now. Definitely open to further ideas.

Thanks again!

**Comment by bhj** [comment]
There is a new logo up along with the updated website! It's using the current app icon with placement similar to the above.

I decided to bold the word "forever" instead because it's ended up becoming something of a guiding principle. Once set up, I want the app to keep working without relying on third parties (or even an internet connection). This affects every part of the design, including being solely file-based (it used to support YouTube channels, but that's another story).

This is far more info than you wanted but it's as good a place as any to elaborate. Thank you again!
