### ISSUE TITLE
Scanning media freezes

### ISSUE THREAD

**Issue by TheRaven117** [bhj/KaraokeEternal#17]
Thank you for your work. I can't seem to scan and add all my karaoke songs to the library. After trying a few times scanning media freezes around 10% of the way through (around file 10k/115k). I was wondering where I was going wrong. Hope everything is going well. Thank you.

Win10 install, ran as admin, can provide sqlite3 file if necessary.

Scanner log 

5/9/2020, 6:17:45 PM [warn] FileScanner: Could not determine artist or title: E:\Karaoke\Karaoke Collection\Len Barry - 1-2-3 [Karaoke].mp3

**Comment by bhj** [comment]
Hi and thanks, hope things are well in your neck of the woods too :)

There is likely a media file that's corrupt, but currently not every file encountered is being logged by default, so please run with [log level](https://www.karaoke-forever.com/docs/#command-line-options) 3 or higher, then the last file listed will be the culprit. You can also run KFS in Command Prompt and watch the output.

Definitely plan to improve the default logging; the warning you mentioned is more of a "hey this won't show up in your library because we couldn't parse the filename" (parsing should also be improved in a future version)

Let me know how it goes!

**Comment by TheRaven117** [comment]
Thank you! That worked great. Appreciate the update.
